import base from '@fanste/config/eslint/base';

export default [
  ...base,
  {
    // Generated by `pnpm db:types` (Supabase CLI); its helper types trip type-aware rules, e.g.
    // `no-redundant-type-constituents` while the schema has no tables.
    ignores: ['src/database.types.ts'],
  },
];
