import base from '@fanste/config/eslint/base';

export default [
  ...base,
  {
    // Generated by `pnpm db:types` (Supabase CLI), not hand-written, so it isn't linted.
    ignores: ['src/database.types.ts'],
  },
];
